### ISSUE TITLE
Make holding "left" and "right" at the same time keep your character still

### ISSUE THREAD

**Issue by TreverWagenhals** [WootingKb/wooting-double-movement#15]
When switching from regular movement to using this program, the biggest difference I noticed that made it hard to keep using is that typically when I hold both left and right movement keys without this program, my character will actually stand still since the two actions cancel each other out. However, in this program, if you hold left and right down at the same time, the priority is given to whichever was last pressed. This has made my movement awkward when I'm directly up against a wall, as I heavily relied on holding both left and right directions down to cancel each other out, and then just lifting one of the directions to apply the one I want. Now when I do this, my character begins to awkwardly walk and drift, and it is a really hard habit to break.

Adding an option to have holding left+right cancel each other out and keep your character still would make this program feel much more like the default settings in my opinion.

Thanks!

**Comment by simon-wh** [comment]
I'm a bit confused by this request given that the behaviour you are desiring is the behaviour of the application. From the sounds of it maybe you haven't fully got all movement keys unbound in-game, causing it to use one of those and keep moving instead of staying still (see [here](https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting#-when-you-walk-its-regular-keyboard-movement-or-worse) for a way to try resolve this).

You can verify for yourself that the app works like this by opening the game controllers window

![image](https://user-images.githubusercontent.com/10797576/115254639-72fd5900-a125-11eb-8df0-bf09a2dc36a9.png)
then clicking on the Device -> Properties -> Test
![image](https://user-images.githubusercontent.com/10797576/115255036-ce2f4b80-a125-11eb-8e89-e94fcf772d8b.png)
You'll see this box with a cross in it. Pressing WASD keys should make it move around, try pressing A and D at the same time, it should return to the centre. Therefore, giving no movement when both are pressed together
