### ISSUE TITLE
Turbo building glitch 

### ISSUE THREAD

**Issue by Damianbalk** [WootingKb/wooting-double-movement#25]
When i use double movement i suddently cant turbobuild while strafing

**Comment by DarrenVs** [comment]
Make use of the default controller settings in Fortnite
![image](https://user-images.githubusercontent.com/2780639/122992028-f8132180-d3a5-11eb-86ff-a074e91d80df.png)

---

The Double Movement app emulates a Gamepad Joystick to create their specific running directions from digital keys.
Due to this emulation, your controller settings in Fortnite may affect the behavior of the game.

To solve this you should change the controller settings to match the behavior of your keyboard and mouse settings. For most players, resetting the controller settings tab will solve their settings conflicts.

**Comment by Dorian11123e** [comment]
yeah i have tried that, still doesent work...?
