### ISSUE TITLE
can't move even with wasd disabled

### ISSUE THREAD

**Issue by BuBBBBB** [WootingKb/wooting-double-movement#33]
hi, can't move or do anything with wooting enabled and wasd disabled and i have locked my input method as well, also tried to do all the downloads and none of them are working and also tried running as admin and that doesn't work, works fine with keys2x, someone help plz

**Comment by DarrenVs** [comment]
This has likely to do with the different gamepads Key2XInput and Wooting Double Movement app emulate. Wooting emulates DS4, where Key2XInput emulates XInput *by default*.
There is likely something preventing the DualShock 4 gamepad from interacting with the game.

## The most common issue here
There is a PlayStation 4 controller connected to your PC.

The Wooting Double Movement app will be fighting with your physical controller for the 'DS Gamepad 1 slot' in Fortnite.
This may also happen if you are running multiple controller emulating(double movement) apps at the same time.

### To solve this

Unplug every controller, re-enable the Wooting DM app, and restart your game.


---

Otherwise you can also checkout the [Troubleshooting Page](https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting) or reach out on [Discord](https://discord.gg/GUz7VbPnvs) in the `#fortnite-double-movement` channel for a Live chat.
