### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Z1X855** [WootingKb/wooting-double-movement#34]
installed, opened and saw this
![изображение_2021-06-22_201355](https://user-images.githubusercontent.com/76178392/122970280-5f28da00-d396-11eb-9da1-fd67866e86bd.png)

**Comment by DarrenVs** [comment]
Try to reinstall the application as administrator.
![image](https://user-images.githubusercontent.com/2780639/122995053-60173700-d3a9-11eb-8d5e-4452856cce76.png)

---

Otherwise checkout [this page](https://github.com/WootingKb/wooting-double-movement/wiki/Troubleshooting#-vigembus-failed-to-install---error-code-2503) on how to perform a manual install for ViGEmBus.
