### ISSUE TITLE
I can't fix player slot 1.

### ISSUE THREAD

**Issue by chirpyyy** [WootingKb/wooting-double-movement#38]
So in Fortnite I couldn't move in game so I went here to try and fix it. When I go to Device manager the Xbox 360 Peripherals don't show up, even when I click "show hidden devices." How can I fix this?

**Comment by DarrenVs** [comment]
Reach out on [Discord](https://discord.gg/GUz7VbPnvs) in the `#double-movement-support` channel for a Live chat.
We can help you out better over there.

---
You should not have any problems with Xbox 360 Peripherals on the latest version of this app as it has switched over to use DS4 since version `v1.2.0`.

Download the latest version of the app [here](https://wooting.io/double-movement), or from the [Release page](https://github.com/WootingKb/wooting-double-movement/releases).
